apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-helm-learning-service
  labels:
    app: helm

spec:
  type: {{ .Values.service.type }}

  selector:
    app: helm

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http