apiVersion: apps/v1
kind: Deployment

metadata:
  name: helm-learning-app
  labels:
    app: helm-learning-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: helm-learning-app

  template:
    metadata:
      labels:
        app: helm-learning-app

    spec:
      containers:
        - name: helm-learning-app
          image: helm:v3
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8085
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
