apiVersion: apps/v1
kind: Deployment

metadata:
  name: payments

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: payments

  template:
    metadata:
      labels:
        app: payments

    spec:
      containers:
        - name: payments
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
