apiVersion: apps/v1
kind: Deployment

metadata:
  name: login
  labels:
    app: login

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: login

  template:
    metadata:
      labels:
        app: login

    spec:
      containers:
        - name: login

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP

          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}

          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
