apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-login-service
  labels:
    app: login

spec:
  type: {{ .Values.service.type }}

  selector:
    app: login

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
